[project]
name = "api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "asyncpg>=0.30.0",
    "fastapi[standard]>=0.117.1",
    "google-genai>=1.52.0",
    "langchain>=0.3.27",
    "langchain-community>=0.3.30",
    "langchain-text-splitters>=0.3.11",
    "pgvector[psycopg]>=0.4.1",
    "psycopg2-binary>=2.9.10",
    "psycopg[async,binary]>=3.2.13",
    "sqlalchemy[asyncio]>=2.0.43",
]

[dependency-groups]
dev = [
    "pyright>=1.1.407",
    "pytest>=8.4.2",
    "pytest-asyncio>=1.2.0",
    "ruff>=0.13.2",
]

[tool.ruff]
line-length = 100
target-version = "py312"
exclude = [
  ".venv",
  "venv",
  "dist",
  "build",
  "__pycache__",
  ".mypy_cache",
  ".pytest_cache",
  ".ruff_cache",
  "migrations",        # nếu bạn không muốn lint alembic revisions
]

[tool.ruff.lint]
select = [
  #"E",    # pycodestyle errors (PEP 8 core)
  "W",    # pycodestyle warnings
  "F",    # pyflakes (unused imports, undefined names...)
  "I",    # isort (sắp xếp import)
  "N",    # pep8-naming (quy ước đặt tên)
  "B",    # flake8-bugbear (bắt lỗi dễ gây bug)
  "UP",   # pyupgrade (gợi ý cú pháp mới, hợp py3.12)
  "SIM",  # simplifications (đơn giản hoá if/logic)
  "RUF",  # ruff-specific rules (best practices)
]
ignore = [
  "B008", # FastAPI dùng Depends(...) trong default param
  "E501", # Line too long
]

[tool.ruff.format]
quote-style = "double"          # dùng "..." thay vì '...'
indent-style = "space"          # 4 spaces
skip-magic-trailing-comma = false
line-ending = "auto"
